# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 394)
        MainWindow.setStyleSheet("QMainWindow {\n   background-color: rgb(0, 79, 5)\n}")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\nbackground-color: rgb(0, 255, 30)\n}")
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")

        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("QWidget {\n   background-color: rgb(9, 9, 9);\n   border-radius: 15px;\n}")
        self.widget.setObjectName("widget")

        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")

        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)

        self.frame1 = QtWidgets.QFrame(self.widget)
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame1, 1, 0, 1, 1)

        self.frame10 = QtWidgets.QFrame(self.widget)
        self.frame10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame10.setObjectName("frame10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.outputLineEdit = QtWidgets.QLineEdit(self.frame10)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.verticalLayout_8.addWidget(self.outputLineEdit)
        self.gridLayout.addWidget(self.frame10, 2, 2, 1, 1)

        self.frame7 = QtWidgets.QFrame(self.widget)
        self.frame7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame7.setObjectName("frame7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.browseOutputButton = QtWidgets.QPushButton(self.frame7)
        self.browseOutputButton.setObjectName("browseOutputButton")
        self.verticalLayout_7.addWidget(self.browseOutputButton)
        self.gridLayout.addWidget(self.frame7, 2, 1, 1, 1)

        self.frame5 = QtWidgets.QFrame(self.widget)
        self.frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame5.setObjectName("frame5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.encryptButton = QtWidgets.QPushButton(self.frame5)
        self.encryptButton.setObjectName("encryptButton")
        self.verticalLayout_10.addWidget(self.encryptButton)
        self.gridLayout.addWidget(self.frame5, 3, 0, 1, 2)

        self.frame6 = QtWidgets.QFrame(self.widget)
        self.frame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame6.setObjectName("frame6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.browseInputButton = QtWidgets.QPushButton(self.frame6)
        self.browseInputButton.setObjectName("browseInputButton")
        self.verticalLayout_5.addWidget(self.browseInputButton)
        self.gridLayout.addWidget(self.frame6, 0, 1, 1, 1)

        self.frame4 = QtWidgets.QFrame(self.widget)
        self.frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame4.setObjectName("frame4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.inputLineEdit = QtWidgets.QLineEdit(self.frame4)
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.verticalLayout_9.addWidget(self.inputLineEdit)
        self.gridLayout.addWidget(self.frame4, 0, 2, 1, 1)

        self.frame3 = QtWidgets.QFrame(self.widget)
        self.frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keyLineEdit = QtWidgets.QLineEdit(self.frame3)
        self.keyLineEdit.setObjectName("keyLineEdit")
        self.verticalLayout.addWidget(self.keyLineEdit)
        self.gridLayout.addWidget(self.frame3, 1, 2, 1, 1)

        self.frame2 = QtWidgets.QFrame(self.widget)
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.browseKeyButton = QtWidgets.QPushButton(self.frame2)
        self.browseKeyButton.setObjectName("browseKeyButton")
        self.verticalLayout_6.addWidget(self.browseKeyButton)
        self.gridLayout.addWidget(self.frame2, 1, 1, 1, 1)

        self.frame8 = QtWidgets.QFrame(self.widget)
        self.frame8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame8.setObjectName("frame8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.decryptButton = QtWidgets.QPushButton(self.frame8)
        self.decryptButton.setObjectName("decryptButton")
        self.verticalLayout_11.addWidget(self.decryptButton)
        self.gridLayout.addWidget(self.frame8, 3, 2, 1, 1)

        self.frame9 = QtWidgets.QFrame(self.widget)
        self.frame9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame9.setObjectName("frame9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame9)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.gridLayout.addWidget(self.frame9, 0, 0, 1, 1)

        self.hexagonWidget = QtWidgets.QWidget(self.widget)
        self.hexagonWidget.setStyleSheet("QWidget {\nbackground-color: rgb(18, 18, 18)\n}")
        self.hexagonWidget.setObjectName("hexagonWidget")
        self.gridLayout.addWidget(self.hexagonWidget, 4, 0, 1, 3)

        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setRowStretch(4, 1)

        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KryptoHex"))
        self.label_3.setText(_translate("MainWindow", "OUTPUT"))
        self.label_2.setText(_translate("MainWindow", "KEYFILE"))
        self.browseOutputButton.setText(_translate("MainWindow", "browse.."))
        self.encryptButton.setText(_translate("MainWindow", "ENCRYPT"))
        self.browseInputButton.setText(_translate("MainWindow", "browse.."))
        self.browseKeyButton.setText(_translate("MainWindow", "browse.."))
        self.decryptButton.setText(_translate("MainWindow", "DECRYPT"))
        self.label.setText(_translate("MainWindow", "SELECT INPUT"))